#! /bin/sh

export PATH=$HOME/.local/bin:$PATH

feh --bg-scale ~/.local/share/wallpapers/Light_Bulb_in_Black_4K_Wallpaper_WithoutKDElogo.jpg
~/.config/polybar/launch.sh &
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
